site_name: "python dev template"

theme:
  name: "material"

site_dir: "public"

nav:
  - welcome: index.md
  - main.py: main.md
  - mymodule: mymodule.md
  - mymodule/rules.py: rules.md
  - mymodule/tools.py: tools.md

plugins:
- search
- mkdocstrings
