version: '3'

tasks:
  format:
    cmds:
      - python -c "from rich import print;print('[sky_blue2]reformatting with black[/sky_blue2]')"
      - black --skip-string-normalization .
    silent: true
  lint:
    cmds:
      - python -c "from rich import print;print('[sky_blue2]analyzing with pylint[/sky_blue2]')"
      - pylint --recursive=y --disable=R,C ./
    silent: true
    ignore_error: true
  find_dead_code:
    cmds:
      - python -c "from rich import print;print('[sky_blue2]analyzing with vulture[/sky_blue2]')"
      - vulture .
    silent: true
    ignore_error: true
  docs:
    cmds:
      - python -c "from rich import print;print('[sky_blue2]building static documentation[/sky_blue2]')"
      - mkdocs build
    silent: true
  update:
    # run in //:
    # deps: [format, lint, version]
    # or run in sequential order:
    cmds:
      - task: format
      - task: lint
      - task: find_dead_code
      - task: docs
    silent: true
