version: '3'

tasks:
  version:
    cmds:
      - python update_version.py
    silent: true
  format:
    cmds:
      - black --skip-string-normalization .
    silent: true
  update:
    deps: [version, format]
    silent: true
